{
 "title": "devices",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "height_distance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"planta1\")\r\n  |> filter(fn: (r) => r[\"measurement\"] == \"height_distance\")"
    }
   ]
  },
  {
   "title": "air_humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"planta1\")\r\n  |> filter(fn: (r) => r[\"measurement\"] == \"air_humidity\")"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"planta1\")\r\n  |> filter(fn: (r) => r[\"measurement\"] == \"temperature\")\r\n"
    }
   ]
  },
  {
   "title": "ground_humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"planta1\")\r\n  |> filter(fn: (r) => r[\"measurement\"] == \"ground_humidity\")"
    }
   ]
  }
 ]
}